apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: upgrade-workflow
spec:
  serviceAccountName: git-bot
  workspaces:
    - name: pipeline-shared-data
      volumeClaimTemplate:
        metadata:
          name: arcas-pvc-pr
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
  pipelineRef:
    name: upgrade-pipeline
