kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: tkg-kind
nodes:
  - role: control-plane
    extraMounts:
      - containerPath: /etc/docker/certs.d/<HARBOR_URL>
        hostPath: /etc/docker/certs.d/<HARBOR_URL>
    image: <HARBOR_URL>/tekton_dep/kindest/node@sha256:f97edf7f7ed53c57762b24f90a34fad101386c5bd4d93baeb45449557148c717
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.configs."<HARBOR_URL>".tls]
      ca_file = "/etc/docker/certs.d/<HARBOR_URL>/<HARBOR_URL>.cert"
