- name: "audisp: verify conf"
  stat:
    path: "/etc/audisp/plugins.d/au-remote.conf"
  register: au_remote_conf
  tags:
  - low

- name: "audisp: set active"
  lineinfile:
    path: "/etc/audisp/plugins.d/au-remote.conf"
    regex: ^active\s+=
    line: active = yes
    state: present
  when:
    - au_remote_conf.stat.exists | bool
    - audit_sp_remote_server != ""
  tags:
  - low

- name: "audisp: set remote_server"
  lineinfile:
    path: "/etc/audisp/plugins.d/au-remote.conf"
    regex: ^remote_server\s+=
    line: "remote_server = {{ audit_sp_remote_server }}"
    state: present
  when:
    - au_remote_conf.stat.exists | bool
    - audit_sp_remote_server != ""
  tags:
  - low