- name: "ca-certs: DoD CA"
  copy:
    src: '{{ item }}'
    dest: /usr/local/share/ca-certificates/
    owner: root
    group: root
    mode: 0644
  with_fileglob:
    - files/ca/*.crt
  notify:
    - update trusted ca debian
