- name: "[Common] pwquality"
  blockinfile:
    dest: /etc/security/pwquality.conf
    insertbefore: EOF
    marker: "# {mark} MCI hardening"
    state: present
    block: |
      ucredit = -1
      lcredit = -1
      dcredit = -1
      ocredit = -1
      difok = 8
      minclass = 4
      maxrepeat = 3
      maxclassrepeat = 4
      minlen = 15
      dictcheck = 1
      enforcing = 1