- name: "rsyslog.d: daemon"
  lineinfile:
    dest: "/etc/rsyslog.d/50-default.conf"
    regexp: '^(#)(daemon\.)([^\s]*)(\s+)(.*)$'
    line: '\2notice\4\5'
    backrefs: yes
    state: present
  tags:
  - medium

- name: "rsyslog.d: auth,authpriv"
  lineinfile:
    dest: "/etc/rsyslog.d/50-default.conf"
    regexp: '^(#)(auth,authpriv\.)([^\s]*)(\s+)(.*)$'
    line: '\2*\4\5'
    backrefs: yes
    state: present
  tags:
  - medium
