apiVersion: v1
kind: Secret
metadata:
  name: git-user-pass
  annotations:
    tekton.dev/git-0: https://gitlab.eng.vmware.com
type: kubernetes.io/basic-auth
stringData:
  username: GITUSER
  password: GITPAT
