apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: ${CLUSTER_NAME}
  namespace: ${NAMESPACE}
  labels:
    tkg.tanzu.vmware.com/cluster-name: '${ CLUSTER_NAME }'
spec:
  distribution:
    version: ${KUBERNETES_VERSION}
  settings:
    network:
      cni:
        name: calico
      pods:
        cidrBlocks:
        - ${CLUSTER_CIDR} #! CIDR block used by Calico
      serviceDomain: ${SERVICE_DOMAIN}
      services:
        cidrBlocks:
        - ${SERVICE_CIDR} #! CIDR block used by Calico
    storage:
      classes: []
      defaultClass: "${DEFAULT_STORAGE_CLASS}"

  topology:
    controlPlane:
      class: ${CONTROL_PLANE_VM_CLASS}
      count: ${CONTROL_PLANE_MACHINE_COUNT}
      storageClass: ${CONTROL_PLANE_STORAGE_CLASS}
    workers:
      class: ${WORKER_VM_CLASS}
      count: ${WORKER_MACHINE_COUNT}
      storageClass: ${WORKER_STORAGE_CLASS}
