---

# Namespace in which to deploy ExternalDNS.
namespace: tanzu-system-service-discovery

# Deployment-related configuration.
deployment:
 args:
   - --source=service
   - --source=ingress
   - --source=contour-httpproxy # Provide this to enable Contour HTTPProxy support. Must have Contour installed or ExternalDNS will fail.
   - --domain-filter=my-zone.example.org # For example, k8s.example.org. Makes ExternalDNS see only the hosted zones matching provided domain, omit to process all available hosted zones.
   - --policy=upsert-only # Prevents ExternalDNS from deleting any records, omit to enable full synchronization.
   - --registry=txt
   - --txt-owner-id=k8s
   - --txt-prefix=external-dns- # Disambiguates TXT records from CNAME records.
   - --provider=rfc2136
   - --rfc2136-host=192.168.0.1
   - --rfc2136-port=53
   - --rfc2136-zone=my-zone.example.org # For example, k8s.example.org.
   - --rfc2136-tsig-secret=REPLACE_ME_WITH_TSIG_SECRET
   - --rfc2136-tsig-secret-alg=hmac-sha256
   - --rfc2136-tsig-keyname=externaldns-key # For example, externaldns-key.
   - --rfc2136-tsig-axfr
 env: []
 securityContext: {}
 volumeMounts: []
 volumes: []