apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: upgrade-pipeline
spec:
  description: >-
    The Pipline to run uprade of mgmt, shared, workload cluster

  workspaces:
    - name: pipeline-shared-data

  params:
    - name: imagename
      description: "The image location"
    - name: giturl
      description: The full http git path
    - name: branch
      description: the branch to clone from. By default, it is set to master.
      default: alpha
    - name: targetcluster
      description: The targetted cluster
    - name: imagepullpolicy
      description: imagepullpolicy for operand image("Always", "IfNotPresent", "Never")
    - name: dindimagename
      description: docker dind image name
  tasks:
    - name: start-prep-workspace
      taskRef:
        name: git-pvtclone
      workspaces:
        - name: task-shared-data
          workspace: pipeline-shared-data
      params:
        - name: imagename
          value: "$(params.imagename)"
        - name: giturl
          value: "$(params.giturl)"
        - name: branch
          value: "$(params.branch)"
        - name: imagepullpolicy
          value: "$(params.imagepullpolicy)"

    - name: start-mgmt-upgrade-only
      when:
        - input: "$(params.targetcluster)"
          operator: in
          values:  [ "mgmt" ]
      taskRef:
        name: mgmt-upgrade
      workspaces:
        - name: task-shared-data
          workspace: pipeline-shared-data
      params:
        - name: imagename
          value: "$(params.imagename)"
        - name: imagepullpolicy
          value: "$(params.imagepullpolicy)"
        - name: dindimagename	
          value: "$(params.dindimagename)"
      runAfter:
          - start-prep-workspace

    - name: start-mgmt-upgrade-all
      when:
        - input: "$(params.targetcluster)"
          operator: in
          values:  [ "all" ]
      taskRef:
        name: mgmt-upgrade
      workspaces:
        - name: task-shared-data
          workspace: pipeline-shared-data
      params:
        - name: imagename
          value: "$(params.imagename)"
        - name: imagepullpolicy
          value: "$(params.imagepullpolicy)"
        - name: dindimagename	
          value: "$(params.dindimagename)"
      runAfter:
          - start-prep-workspace

    - name: start-shared-upgrade
      when:
        - input: "$(params.targetcluster)"
          operator: in
          values:  [ "all" ]
      taskRef:
          name: shared-upgrade
      workspaces:
          - name: task-shared-data
            workspace: pipeline-shared-data
      params:
        - name: imagename
          value: $(params.imagename)
        - name: imagepullpolicy
          value: "$(params.imagepullpolicy)"
        - name: dindimagename	
          value: "$(params.dindimagename)"
      runAfter:
          - start-mgmt-upgrade-all

    - name: start-workload-upgrade
      when:
        - input: "$(params.targetcluster)"
          operator: in
          values:  [ "all" ]
      taskRef:
          name: workload-upgrade
      workspaces:
          - name: task-shared-data
            workspace: pipeline-shared-data
      params:
        - name: imagename
          value: $(params.imagename)
        - name: imagepullpolicy
          value: "$(params.imagepullpolicy)"
        - name: dindimagename	
          value: "$(params.dindimagename)"

      runAfter:
          -  start-shared-upgrade

    - name: start-extns-upgrade
      when:
          - input: "$(params.targetcluster)"
            operator: in
            values: [ "all" ]
      taskRef:
        name: extns-upgrade
      workspaces:
        - name: task-shared-data
          workspace: pipeline-shared-data
      params:
        - name: imagename
          value: $(params.imagename)
        - name: imagepullpolicy
          value: "$(params.imagepullpolicy)"
        - name: dindimagename	
          value: "$(params.dindimagename)"

      runAfter:
        - start-workload-upgrade

  finally:
      - name: gitcommit
        taskRef:
          name: git-commit-task
        workspaces:
          - name: task-shared-data
            workspace: pipeline-shared-data
        params:
          - name: imagename
            value: "$(params.imagename)"
          - name: imagepullpolicy
            value: "$(params.imagepullpolicy)"
          - name: branch
            value: "$(params.branch)"
