#@ load("@ytt:data", "data")
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: tkgs-bringup-day0-
spec:
  pipelineRef:
    name: day0-pipeline-tkgs
  params:
    - name: imagename
      value: #@ data.values.imagename
    - name: giturl
      value: #@ "https://" + data.values.git.host + "/" + data.values.git.repository
    - name: branch
      value: #@ data.values.git.branch
    - name: imagepullpolicy
      value: #@ data.values.imagepullpolicy
  timeout: 2h0m0s
  workspaces:
    - name: pipeline-shared-data
      persistentVolumeClaim:
        claimName: tekton-day0
  serviceAccountName: git-bot

