#@ load("@ytt:data", "data")
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: tkgm-upgrade-day2-
spec:
  pipelineRef:
    name: upgrade-pipeline
  params:
    - name: imagename
      value: #@ data.values.imagename
    - name: giturl
      value: #@ "https://" + data.values.git.host + "/" + data.values.git.repository
    - name: branch
      value: #@ data.values.git.branch
    - name: targetcluster
      value: mgmt
  workspaces:
    - name: pipeline-shared-data
      persistentVolumeClaim:
        claimName: tekton-day0
  serviceAccountName: git-bot

