#  Copyright 2021 VMware, Inc
#  SPDX-License-Identifier: BSD-2-Clause

apiVersion: v1
kind: Secret
metadata:
  name: git-user-pass
  annotations:
    tekton.dev/git-0: https://GIT_FQDN
type: kubernetes.io/basic-auth
stringData:
  username: GITUSER
  password: GITPAT
