apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: tkgm-bringup-day0-
spec:
  pipelineRef:
    name: day0-pipeline
  params:

  - name: giturl
    value: ""
  - name: branch
    value: ""

  timeout: 3h0m0s
  workspaces:
  - name: pipeline-shared-data
    persistentVolumeClaim:
      claimName: tekton-day0
  serviceAccountName: git-bot
