#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")
#@ load("/02_addons/avi/spec.lib.yaml","avi_configs_spec","avi_credentials","avi_certificate")

#@ def update_mc_akodeploymentconfig():
#@overlay/match missing_ok=True
clusterSelector:
  #@overlay/replace
  matchLabels:
    #@ if data.values.TKG_CLUSTER_ROLE != "workload":
    cluster-role.tkg.tanzu.vmware.com/management: ""
    #@ end
#@overlay/match missing_ok=True
dataNetwork:
  #@overlay/replace
  name: #@ data.values.AVI_MANAGEMENT_CLUSTER_VIP_NETWORK_NAME
  cidr: #@ data.values.AVI_MANAGEMENT_CLUSTER_VIP_NETWORK_CIDR 
#@ end

#@ def akoconfigyaml():
---
apiVersion: networking.tkg.tanzu.vmware.com/v1alpha1
kind: AKODeploymentConfig
metadata:
  name: install-ako-for-all
spec: #@ avi_configs_spec()
---
apiVersion: networking.tkg.tanzu.vmware.com/v1alpha1
kind: AKODeploymentConfig
metadata:
  name: install-ako-for-management-cluster
spec: #@ overlay.apply(avi_configs_spec(), update_mc_akodeploymentconfig())
--- #@ avi_credentials()
--- #@ avi_certificate()
#@ end