apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: day0-pipeline
spec:
  description: >-
    The Pipline to run e2e TKG 1.4.x bringup on vSphere DVS Internet Lab.
  workspaces:
    - name: pipeline-shared-data
  results:
    - name: imagename
      description: obtained imagename from worker
      value: $(tasks.prepare-workspace.results.theimagename)

  params:
    
    - name: giturl
      description: The full http git path
    - name: branch
      description: the branch to clone from. By default, it is set to master.
      default: alpha
    - name: imagepullpolicy
      description: imagepullpolicy for operand image("Always", "IfNotPresent", "Never")
      default: "Never"

  tasks:
    - name: prepare-workspace
      taskRef:
        name: git-pvtclone
      workspaces:
        - name: task-shared-data
          workspace: pipeline-shared-data
      params:
        - name: giturl
          value: "$(params.giturl)"
        - name: branch
          value: "$(params.branch)"

    - name: configure-avi
      taskRef:
        name: avi-setup-task
      workspaces:
        - name: task-shared-data
          workspace: pipeline-shared-data
      params:
        - name: imagename
          value: "$(tasks.prepare-workspace.results.theimagename)"
      runAfter:
          - prepare-workspace

    - name: mgmt-cluster-creation
      taskRef:
        name: mgmt-create
      workspaces:
        - name: task-shared-data
          workspace: pipeline-shared-data
      params:
        - name: imagename
          value: "$(tasks.prepare-workspace.results.theimagename)"
      runAfter:
            - configure-avi

    - name: shared-service-cluster-creation
      taskRef:
        name: sharedcluster-create
      workspaces:
        - name: task-shared-data
          workspace: pipeline-shared-data
      params:
        - name: imagename
          value: "$(tasks.prepare-workspace.results.theimagename)"
      runAfter:
            - mgmt-cluster-creation

    - name: workload-cluster-creation
      taskRef:
        name: workload-create
      workspaces:
          - name: task-shared-data
            workspace: pipeline-shared-data
      params:
        - name: imagename
          value: "$(tasks.prepare-workspace.results.theimagename)"
      runAfter:
            - shared-service-cluster-creation

    - name: extensions-deploy
      taskRef:
        name: extns-setup
      workspaces:
          - name: task-shared-data
            workspace: pipeline-shared-data
      params:
        - name: imagename
          value: "$(tasks.prepare-workspace.results.theimagename)"
      runAfter:
            - workload-cluster-creation
  finally:
      - name: ops-git-commit
        taskRef:
            name: git-commit-task
        workspaces:
          - name: task-shared-data
            workspace: pipeline-shared-data
        params:

          - name: branch
            value: "$(params.branch)"
