apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: day0-pipeline-tkgs
spec:
  description: >-
    The Pipline to run e2e TKGs 1.4.x bringup on vSphere DVS Internet Lab.
  workspaces:
    - name: pipeline-shared-data
  results:
    - name: imagename
      description: the imagename obtained from worker
      value: $(tasks.prepare-workspace.results.theimagename)
  params:
    - name: giturl
      description: The full http git path
    - name: branch
      description: the branch to clone from. By default, it is set to master.
      default: alpha

  tasks:
    - name: prepare-workspace
      taskRef:
        name: git-pvtclone
      workspaces:
        - name: task-shared-data
          workspace: pipeline-shared-data
      params:
        - name: giturl
          value: "$(params.giturl)"
        - name: branch
          value: "$(params.branch)"


    - name: configure-avi
      taskRef:
        name: avi-setup-task
      workspaces:
        - name: task-shared-data
          workspace: pipeline-shared-data
      params:
        - name: imagename
          value: "$(tasks.prepare-workspace.results.theimagename)"
      runAfter:
        - prepare-workspace

    - name: avi-wcp-configuration
      taskRef:
        name: tkgs-supervisor-create
      workspaces:
        - name: task-shared-data
          workspace: pipeline-shared-data
      params:
        - name: imagename
          value: "$(tasks.prepare-workspace.results.theimagename)"
      runAfter:
        - configure-avi

    - name: enabling-wcp
      taskRef:
        name: enable-wcp
      workspaces:
        - name: task-shared-data
          workspace: pipeline-shared-data
      params:
        - name: imagename
          value: "$(tasks.prepare-workspace.results.theimagename)"
      runAfter:
        - avi-wcp-configuration

    - name: setup-ns-workload
      taskRef:
        name: tkgs-wld-ns-setup
      workspaces:
        - name: task-shared-data
          workspace: pipeline-shared-data
      params:
        - name: imagename
          value: "$(tasks.prepare-workspace.results.theimagename)"
      runAfter:
        - enabling-wcp

    - name: workload-cluster-creation
      taskRef:
        name: tkgs-wld-setup
      workspaces:
        - name: task-shared-data
          workspace: pipeline-shared-data
      params:
        - name: imagename
          value: "$(tasks.prepare-workspace.results.theimagename)"
      runAfter:
        - setup-ns-workload

    - name: extns-deploy
      taskRef:
        name: tkgs-extns-setup
      workspaces:
        - name: task-shared-data
          workspace: pipeline-shared-data
      params:
        - name: imagename
          value: "$(tasks.prepare-workspace.results.theimagename)"
      runAfter:
        - workload-cluster-creation
