- name: restart auditd
  command: service auditd restart
  args:
    warn: no

- name: augenrules load
  command: augenrules --load
  notify:
  - restart auditd
  
- name: remove apt dependencies
  apt:
    autoremove: yes
    purge: yes

- name: update grub
  command: update-grub 

- name: update trusted ca debian
  command: update-ca-certificates