#@ load("@ytt:data", "data")
---
apiVersion: polling.tekton.dev/v1alpha1
kind: Repository
metadata:
  name: monitor-bringup-mesage
spec:
  url: #@ "https://" + data.values.git.host + "/" + data.values.git.repository
  ref: #@ data.values.git.branch
  frequency: 2m
  type: gitlab
  pipelineRef:
    name: trigger-bringup-pipeline
    params:
    - name: message
      expression: commit.message
    workspaces:
      - name: pipeline-shared-data
        persistentVolumeClaim:
          claimName: tekton-day0

  auth:
    secretRef:
      name: git-user-pass
    key: password

