clientOptions:
  cli:
    repositories:
    - gcpPluginRepository:
        bucketName: tanzu-cli
        name: core
    - gcpPluginRepository:
        bucketName: tanzu-cli-tkg-plugins
        name: tkg
current: =
metadata:
  creationTimestamp: null
servers:
- managementClusterOpts:
    context: 
    path: /root/.kube-tkg/config
  name: 
  type: managementcluster
