apiVersion: run.tanzu.vmware.com/v1alpha2
default:
  k8sVersion: v1.22.5+vmware.1-tkg.1
release:
  version: v1.5.0
components:
  aad-pod-identity:
  - version: v1.8.0+vmware.1
    images:
      micImage:
        imagePath: cluster-api/mic
        tag: v1.8.0_vmware.1
      nmiImage:
        imagePath: cluster-api/nmi
        tag: v1.8.0_vmware.1
  alertmanager:
  - version: v0.22.2+vmware.1
    images:
      alertmanagerImage:
        imagePath: prometheus/alertmanager
        tag: v0.22.2_vmware.1
  cadvisor:
  - version: v0.39.1+vmware.1
    images:
      cadvisorImage:
        imagePath: prometheus/cadvisor
        tag: v0.39.1_vmware.1
  cloud-provider-azure:
  - version: v0.7.4+vmware.1
    images:
      ccmAzureControllerImage:
        imagePath: azure-cloud-controller-manager
        tag: v0.7.4_vmware.1
      ccmAzureNodeImage:
        imagePath: azure-cloud-node-manager
        tag: v0.7.4_vmware.1
  cluster-api-provider-azure:
  - version: v1.0.1+vmware.1
    images:
      capzControllerImage:
        imagePath: cluster-api/cluster-api-azure-controller
        tag: v1.0.1_vmware.1
  cluster-api-provider-bringyourownhost:
  - version: v0.1.0+vmware.3
    images:
      byohControllerImage:
        imagePath: cluster-api/cluster-api-byoh-controller
        tag: v0.1.0_vmware.3
      byohImgpkgBundle:
        imagePath: cluster-api/byoh-bundle-ubuntu_20.04.1_x86-64_k8s_v1.22.3
        tag: v0.1.0_vmware.3
  cluster_api:
  - version: v1.0.1+vmware.1
    images:
      cabpkControllerImage:
        imagePath: cluster-api/kubeadm-bootstrap-controller
        tag: v1.0.1_vmware.1
      capdManagerImage:
        imagePath: cluster-api/capd-manager
        tag: v1.0.1_vmware.1
      capiControllerImage:
        imagePath: cluster-api/cluster-api-controller
        tag: v1.0.1_vmware.1
      kcpControllerImage:
        imagePath: cluster-api/kubeadm-control-plane-controller
        tag: v1.0.1_vmware.1
  cluster_api_aws:
  - version: v1.2.0+vmware.1
    images:
      capaControllerImage:
        imagePath: cluster-api/cluster-api-aws-controller
        tag: v1.2.0_vmware.1
  cluster_api_vsphere:
  - version: v1.0.2+vmware.1
    images:
      capvControllerImage:
        imagePath: cluster-api/cluster-api-vsphere-controller
        tag: v1.0.2_vmware.1
  configmap-reload:
  - version: v0.5.0+vmware.2
    images:
      configmapReloadImage:
        imagePath: prometheus/configmap-reload
        tag: v0.5.0_vmware.2
  contour:
  - version: v1.17.2+vmware.1
    images:
      contourImage:
        imagePath: contour
        tag: v1.17.2_vmware.1
  - version: v1.18.2+vmware.1
    images:
      contourImage:
        imagePath: contour
        tag: v1.18.2_vmware.1
  crash-diagnostics:
  - version: v0.3.7+vmware.3
  envoy:
  - version: v1.18.4+vmware.1
    images:
      envoyImage:
        imagePath: envoy
        tag: v1.18.4_vmware.1
  - version: v1.19.1+vmware.1
    images:
      envoyImage:
        imagePath: envoy
        tag: v1.19.1_vmware.1
  external-dns:
  - version: v0.10.0+vmware.1
    images:
      externalDNSImage:
        imagePath: external-dns
        tag: v0.10.0_vmware.1
  fluent-bit:
  - version: v1.7.5+vmware.2
    images:
      fluentBitImage:
        imagePath: fluent-bit
        tag: v1.7.5_vmware.2
  gangway:
  - version: v3.2.0+vmware.2
    images:
      gangwayImage:
        imagePath: gangway
        tag: v3.2.0_vmware.2
  grafana:
  - version: v7.5.7+vmware.2
    images:
      grafanaImage:
        imagePath: grafana/grafana
        tag: v7.5.7_vmware.2
  harbor:
  - version: v2.3.3+vmware.1
    images:
      harborChartMuseumImage:
        imagePath: harbor/chartmuseum-photon
        tag: v2.3.3_vmware.1
      harborCoreImage:
        imagePath: harbor/harbor-core
        tag: v2.3.3_vmware.1
      harborDatabaseImage:
        imagePath: harbor/harbor-db
        tag: v2.3.3_vmware.1
      harborExporterImage:
        imagePath: harbor/harbor-exporter
        tag: v2.3.3_vmware.1
      harborJobServiceImage:
        imagePath: harbor/harbor-jobservice
        tag: v2.3.3_vmware.1
      harborLogImage:
        imagePath: harbor/harbor-log
        tag: v2.3.3_vmware.1
      harborNginxImage:
        imagePath: harbor/nginx-photon
        tag: v2.3.3_vmware.1
      harborNotaryServerImage:
        imagePath: harbor/notary-server-photon
        tag: v2.3.3_vmware.1
      harborNotarySignerImage:
        imagePath: harbor/notary-signer-photon
        tag: v2.3.3_vmware.1
      harborPortalImage:
        imagePath: harbor/harbor-portal
        tag: v2.3.3_vmware.1
      harborPrepareImage:
        imagePath: harbor/prepare
        tag: v2.3.3_vmware.1
      harborRedisImage:
        imagePath: harbor/redis-photon
        tag: v2.3.3_vmware.1
      harborRegistryCtlImage:
        imagePath: harbor/harbor-registryctl
        tag: v2.3.3_vmware.1
      harborRegistryImage:
        imagePath: harbor/registry-photon
        tag: v2.3.3_vmware.1
      harborTrivyAdapterImage:
        imagePath: harbor/trivy-adapter-photon
        tag: v2.3.3_vmware.1
  image-builder:
  - version: v0.1.11+vmware.3
    images:
      imagebuilder-tar:
        imagePath: image-builder
        tag: v0.1.11_vmware.3
  imgpkg:
  - version: v0.18.0+vmware.1
  jetstack_cert-manager:
  - version: v1.5.3+vmware.2
    images:
      certMgrControllerImage:
        imagePath: cert-manager-controller
        tag: v1.5.3_vmware.2
      certMgrInjectorImage:
        imagePath: cert-manager-cainjector
        tag: v1.5.3_vmware.2
      certMgrWebhookImage:
        imagePath: cert-manager-webhook
        tag: v1.5.3_vmware.2
  k8s-sidecar:
  - version: v1.12.1+vmware.2
    images:
      k8sSidecarImage:
        imagePath: grafana/k8s-sidecar
        tag: v1.12.1_vmware.2
  k14s_kapp:
  - version: v0.42.0+vmware.1
  k14s_ytt:
  - version: v0.35.1+vmware.1
  kbld:
  - version: v0.31.0+vmware.1
  kube-state-metrics:
  - version: v1.9.8+vmware.1
    images:
      kubeStateMetricsImage:
        imagePath: prometheus/kube-state-metrics
        tag: v1.9.8_vmware.1
  kube-vip:
  - version: v0.3.3+vmware.1
    images:
      kubeVipImage:
        imagePath: kube-vip
        tag: v0.3.3_vmware.1
  kube_rbac_proxy:
  - version: v0.8.0+vmware.1
    images:
      kubeRbacProxyControllerImage:
        imagePath: kube-rbac-proxy
        tag: v0.8.0_vmware.1
      kubeRbacProxyControllerImageCapi:
        imagePath: cluster-api/kube-rbac-proxy
        tag: v0.8.0_vmware.1
  kubernetes-sigs_kind:
  - version: v1.22.5+vmware.1_v0.11.1
    images:
      kindNodeImage:
        imagePath: kind/node
        tag: v1.22.5_vmware.1_v0.11.1
  kubernetes_autoscaler:
  - version: v1.22.0+vmware.1
    images:
      kubernetesAutoscalerImage:
        imagePath: cluster-autoscaler
        tag: v1.22.0_vmware.1
    metadata:
      k8sversion: v1.22.3+vmware.1
  - version: v1.21.0+vmware.1
    images:
      kubernetesAutoscalerImage:
        imagePath: cluster-autoscaler
        tag: v1.21.0_vmware.1
    metadata:
      k8sversion: v1.21.1+vmware.1
  - version: v1.20.0+vmware.1
    images:
      kubernetesAutoscalerImage:
        imagePath: cluster-autoscaler
        tag: v1.20.0_vmware.1
    metadata:
      k8sversion: v1.20.4+vmware.1
  multus-cni:
  - version: v3.7.1+vmware.2
    images:
      multusCniImage:
        imagePath: multus-cni
        tag: v3.7.1_vmware.2
  prometheus:
  - version: v2.27.0+vmware.1
    images:
      prometheusImage:
        imagePath: prometheus/prometheus
        tag: v2.27.0_vmware.1
  prometheus_node_exporter:
  - version: v1.1.2+vmware.1
    images:
      prometheusNodeExporterImage:
        imagePath: prometheus/prometheus_node_exporter
        tag: v1.1.2_vmware.1
  pushgateway:
  - version: v1.4.0+vmware.1
    images:
      pushgatewayImage:
        imagePath: prometheus/pushgateway
        tag: v1.4.0_vmware.1
  sonobuoy:
  - version: v0.54.0+vmware.1
    images:
      sonobuoyImage:
        imagePath: sonobuoy
        tag: v0.54.0_vmware.1
  standalone-plugins-package:
  - version: v0.11.1-90-g43d6060e-standalone-plugins
    images:
      standalone-plugins.tanzu.vmware.com:
        imagePath: packages/standalone/standalone-plugins
        tag: v0.11.1-90-g43d6060e_vmware.1
  tanzu-framework:
  - version: v0.11.1-90-g43d6060e
    images:
      capabilitiesImage:
        imagePath: tanzu_core/capabilities/capabilities-controller-manager
        tag: v0.11.1-90-g43d6060e
      clipluginsClusterDarwinAmd64Image:
        imagePath: tanzu_core/tanzu-cli-plugins/cluster-darwin-amd64
        tag: v0.11.1-90-g43d6060e
      clipluginsClusterLinuxAmd64Image:
        imagePath: tanzu_core/tanzu-cli-plugins/cluster-linux-amd64
        tag: v0.11.1-90-g43d6060e
      clipluginsClusterWindowsAmd64Image:
        imagePath: tanzu_core/tanzu-cli-plugins/cluster-windows-amd64
        tag: v0.11.1-90-g43d6060e
      clipluginsKubernetesReleaseDarwinAmd64Image:
        imagePath: tanzu_core/tanzu-cli-plugins/kubernetes-release-darwin-amd64
        tag: v0.11.1-90-g43d6060e
      clipluginsKubernetesReleaseLinuxAmd64Image:
        imagePath: tanzu_core/tanzu-cli-plugins/kubernetes-release-linux-amd64
        tag: v0.11.1-90-g43d6060e
      clipluginsKubernetesReleaseWindowsAmd64Image:
        imagePath: tanzu_core/tanzu-cli-plugins/kubernetes-release-windows-amd64
        tag: v0.11.1-90-g43d6060e
      clipluginsLoginDarwinAmd64Image:
        imagePath: tanzu_core/tanzu-cli-plugins/login-darwin-amd64
        tag: v0.11.1-90-g43d6060e
      clipluginsLoginLinuxAmd64Image:
        imagePath: tanzu_core/tanzu-cli-plugins/login-linux-amd64
        tag: v0.11.1-90-g43d6060e
      clipluginsLoginWindowsAmd64Image:
        imagePath: tanzu_core/tanzu-cli-plugins/login-windows-amd64
        tag: v0.11.1-90-g43d6060e
      clipluginsManagementClusterDarwinAmd64Image:
        imagePath: tanzu_core/tanzu-cli-plugins/management-cluster-darwin-amd64
        tag: v0.11.1-90-g43d6060e
      clipluginsManagementClusterLinuxAmd64Image:
        imagePath: tanzu_core/tanzu-cli-plugins/management-cluster-linux-amd64
        tag: v0.11.1-90-g43d6060e
      clipluginsManagementClusterWindowsAmd64Image:
        imagePath: tanzu_core/tanzu-cli-plugins/management-cluster-windows-amd64
        tag: v0.11.1-90-g43d6060e
      clipluginsPackageDarwinAmd64Image:
        imagePath: tanzu_core/tanzu-cli-plugins/package-darwin-amd64
        tag: v0.11.1-90-g43d6060e
      clipluginsPackageLinuxAmd64Image:
        imagePath: tanzu_core/tanzu-cli-plugins/package-linux-amd64
        tag: v0.11.1-90-g43d6060e
      clipluginsPackageWindowsAmd64Image:
        imagePath: tanzu_core/tanzu-cli-plugins/package-windows-amd64
        tag: v0.11.1-90-g43d6060e
      clipluginsPinnipedAuthDarwinAmd64Image:
        imagePath: tanzu_core/tanzu-cli-plugins/pinniped-auth-darwin-amd64
        tag: v0.11.1-90-g43d6060e
      clipluginsPinnipedAuthLinuxAmd64Image:
        imagePath: tanzu_core/tanzu-cli-plugins/pinniped-auth-linux-amd64
        tag: v0.11.1-90-g43d6060e
      clipluginsPinnipedAuthWindowsAmd64Image:
        imagePath: tanzu_core/tanzu-cli-plugins/pinniped-auth-windows-amd64
        tag: v0.11.1-90-g43d6060e
      clipluginsSecretDarwinAmd64Image:
        imagePath: tanzu_core/tanzu-cli-plugins/secret-darwin-amd64
        tag: v0.11.1-90-g43d6060e
      clipluginsSecretLinuxAmd64Image:
        imagePath: tanzu_core/tanzu-cli-plugins/secret-linux-amd64
        tag: v0.11.1-90-g43d6060e
      clipluginsSecretWindowsAmd64Image:
        imagePath: tanzu_core/tanzu-cli-plugins/secret-windows-amd64
        tag: v0.11.1-90-g43d6060e
      featuregatesImage:
        imagePath: tanzu_core/featuregates/featuregates-controller-manager
        tag: v0.11.1-90-g43d6060e
      providerTemplateImage:
        imagePath: tanzu_core/provider/provider-templates
        tag: v0.11.1-90-g43d6060e
      tkrImage:
        imagePath: tanzu_core/tkr/tkr-controller-manager
        tag: v0.11.1-90-g43d6060e
  tanzu-framework-management-packages:
  - version: v0.11.1-90-g43d6060e
    images:
      tanzuFrameworkManagementPackageRepositoryImage:
        imagePath: packages/management/repo
        tag: v0.11.1-90-g43d6060e
  tkg-bom:
  - version: v1.5.0
    images:
      tkgBomImage:
        imagePath: tkg-bom
        tag: v1.5.0
  tkg-standard-packages:
  - version: v1.5.0
    images:
      tanzuStandardPackageRepositoryImage:
        imagePath: packages/standard/repo
        tag: v1.5.0
  tkg_telemetry:
  - version: v1.5.0+vmware.1
    images:
      tkgTelemetryImage:
        imagePath: tkg-telemetry
        tag: v1.5.0_vmware.1
  velero:
  - version: v1.7.0+vmware.1
    images:
      veleroImage:
        imagePath: velero/velero
        tag: v1.7.0_vmware.1
      veleroResticRestoreHelperImage:
        imagePath: velero/velero-restic-restore-helper
        tag: v1.7.0_vmware.1
  velero-plugin-for-aws:
  - version: v1.3.0+vmware.1
    images:
      veleroPluginForAwsImage:
        imagePath: velero/velero-plugin-for-aws
        tag: v1.3.0_vmware.1
  velero-plugin-for-microsoft-azure:
  - version: v1.3.0+vmware.1
    images:
      veleroPluginForMicrosoftAzureImage:
        imagePath: velero/velero-plugin-for-microsoft-azure
        tag: v1.3.0_vmware.1
  velero-plugin-for-vsphere:
  - version: v1.3.0+vmware.1
    images:
      veleroBackupDriverImage:
        imagePath: velero/backup-driver
        tag: v1.3.0_vmware.1
      veleroDataManagerForPluginImage:
        imagePath: velero/data-manager-for-plugin
        tag: v1.3.0_vmware.1
      veleroPluginForVsphereImage:
        imagePath: velero/velero-plugin-for-vsphere
        tag: v1.3.0_vmware.1
  vendir:
  - version: v0.23.0+vmware.1
kindKubeadmConfigSpec:
- 'kind: Cluster'
- 'apiVersion: kind.x-k8s.io/v1alpha4'
- 'kubeadmConfigPatches:'
- '- |'
- '  apiVersion: kubeadm.k8s.io/v1beta2'
- '  kind: ClusterConfiguration'
- '  imageRepository: projects.registry.vmware.com/tkg'
- '  etcd:'
- '    local:'
- '      imageRepository: projects.registry.vmware.com/tkg'
- '      imageTag: v3.5.0_vmware.7'
- '  dns:'
- '    type: CoreDNS'
- '    imageRepository: projects.registry.vmware.com/tkg'
- '    imageTag: v1.8.4_vmware.7'
imageConfig:
  imageRepository: projects.registry.vmware.com/tkg
tkr-bom:
  imagePath: tkr-bom
tkr-compatibility:
  imagePath: tkr-compatibility
