apiVersion: run.tanzu.vmware.com/v1alpha2
release:
  version: v1.22.5+vmware.1-tkg.1
components:
  ako-operator:
  - version: v1.5.0+vmware.4
    images:
      akoOperatorImage:
        imagePath: ako-operator
        tag: v1.5.0_vmware.4
  antrea:
  - version: v1.2.3+vmware.4-advanced
    images:
      antreaImage:
        imagePath: antrea-advanced-debian
        tag: v1.2.3_vmware.4
  calico_all:
  - version: v3.19.1+vmware.1
    images:
      calicoCniImage:
        imagePath: calico-all/cni-plugin
        tag: v3.19.1_vmware.1
      calicoKubecontrollerImage:
        imagePath: calico-all/kube-controllers
        tag: v3.19.1_vmware.1
      calicoNodeImage:
        imagePath: calico-all/node
        tag: v3.19.1_vmware.1
      calicoPodDaemonImage:
        imagePath: calico-all/pod2daemon
        tag: v3.19.1_vmware.1
  carvel-secretgen-controller:
  - version: v0.7.1+vmware.1
    images:
      secretgenControllerImage:
        imagePath: secretgen-controller
        tag: v0.7.1_vmware.1
  cloud_provider_vsphere:
  - version: v1.22.4+vmware.1
    images:
      ccmControllerImage:
        imagePath: ccm/manager
        tag: v1.22.4_vmware.1
  cni_plugins:
  - version: v0.9.1+vmware.8
  containerd:
  - version: v1.5.9+vmware.1
  coredns:
  - version: v1.8.4+vmware.7
    images:
      coredns:
        imagePath: coredns
        tag: v1.8.4_vmware.7
  cri_tools:
  - version: v1.21.0+vmware.7
  csi_attacher:
  - version: v3.3.0+vmware.1
    images:
      csiAttacherImage:
        imagePath: csi/csi-attacher
        tag: v3.3.0_vmware.1
  csi_livenessprobe:
  - version: v2.4.0+vmware.1
    images:
      csiLivenessProbeImage:
        imagePath: csi/csi-livenessprobe
        tag: v2.4.0_vmware.1
  csi_node_driver_registrar:
  - version: v2.3.0+vmware.1
    images:
      csiNodeDriverRegistrarImage:
        imagePath: csi/csi-node-driver-registrar
        tag: v2.3.0_vmware.1
  csi_provisioner:
  - version: v3.0.0+vmware.1
    images:
      csiProvisonerImage:
        imagePath: csi/csi-provisioner
        tag: v3.0.0_vmware.1
  dex:
  - version: v2.30.2+vmware.1
    images:
      dexImage:
        imagePath: dex
        tag: v2.30.2_vmware.1
  etcd:
  - version: v3.5.0+vmware.7
    images:
      etcd:
        imagePath: etcd
        tag: v3.5.0_vmware.7
  kapp-controller:
  - version: v0.30.0+vmware.1
    images:
      kappControllerImage:
        imagePath: kapp-controller
        tag: v0.30.0_vmware.1
  kubernetes:
  - version: v1.22.5+vmware.1
    images:
      kubeAPIServer:
        imagePath: kube-apiserver
        tag: v1.22.5_vmware.1
      kubeControllerManager:
        imagePath: kube-controller-manager
        tag: v1.22.5_vmware.1
      kubeProxy:
        imagePath: kube-proxy
        tag: v1.22.5_vmware.1
      kubeScheduler:
        imagePath: kube-scheduler
        tag: v1.22.5_vmware.1
      pause:
        imagePath: pause
        tag: "3.5"
      pause_windows_1809:
        imagePath: pause
        tag: 3.5-windows-amd64
      pause_windows_1903:
        imagePath: pause
        tag: 3.5-windows-amd64-1903
      pause_windows_1909:
        imagePath: pause
        tag: 3.5-windows-amd64-1909
      pause_windows_2004:
        imagePath: pause
        tag: 3.5-windows-amd64-2004
  kubernetes-csi_external-resizer:
  - version: v1.3.0+vmware.1
    images:
      csiExternalResizer:
        imagePath: kubernetes-csi_external-resizer
        tag: v1.3.0_vmware.1
  kubernetes-sigs_kind:
  - version: v1.22.5+vmware.1_v0.11.1
    images:
      kindNodeImage:
        imagePath: kind/node
        tag: v1.22.5_vmware.1_v0.11.1
  load-balancer-and-ingress-service:
  - version: v1.6.1+vmware.2
    images:
      loadBalancerAndIngressServiceImage:
        imagePath: ako
        tag: v1.6.1_vmware.2
  metrics-server:
  - version: v0.5.1+vmware.1
    images:
      metricsServerImage:
        imagePath: metrics-server
        tag: v0.5.1_vmware.1
  pinniped:
  - version: v0.12.0+vmware.1
    images:
      pinnipedImage:
        imagePath: pinniped
        tag: v0.12.0_vmware.1
  pinniped-post-deploy:
  - version: v0.11.1
    images:
      tkgPinnipedPostDeployImage:
        imagePath: tanzu_core/addons/tkg-pinniped-post-deploy
        tag: v0.11.1
  tanzu-framework-addons:
  - version: v0.11.1-90-g43d6060e
    images:
      tanzuAddonsManagerImage:
        imagePath: tanzu_core/addons/tanzu-addons-manager
        tag: v0.11.1-90-g43d6060e
      tkgPinnipedPostDeployImage:
        imagePath: tanzu_core/addons/tkg-pinniped-post-deploy
        tag: v0.11.1-90-g43d6060e
  tkg-core-packages:
  - version: v1.22.5+vmware.1-tkg.1
    images:
      addons-manager.tanzu.vmware.com:
        imagePath: packages/core/addons-manager
        tag: v1.5.0_vmware.1-tkg.1
      ako-operator.tanzu.vmware.com:
        imagePath: packages/core/ako-operator
        tag: v1.5.0_vmware.4-tkg.1
      antrea.tanzu.vmware.com:
        imagePath: packages/core/antrea
        tag: v1.2.3_vmware.4-tkg.1-advanced
      calico.tanzu.vmware.com:
        imagePath: packages/core/calico
        tag: v3.19.1_vmware.1-tkg.3
      kapp-controller.tanzu.vmware.com:
        imagePath: packages/core/kapp-controller
        tag: v0.30.0_vmware.1-tkg.1
      load-balancer-and-ingress-service.tanzu.vmware.com:
        imagePath: packages/core/load-balancer-and-ingress-service
        tag: v1.6.1_vmware.2-tkg.3
      metrics-server.tanzu.vmware.com:
        imagePath: packages/core/metrics-server
        tag: v0.5.1_vmware.1-tkg.1
      pinniped.tanzu.vmware.com:
        imagePath: packages/core/pinniped
        tag: v0.12.0_vmware.1-tkg.1
      secretgen-controller.tanzu.vmware.com:
        imagePath: packages/core/secretgen-controller
        tag: v0.7.1_vmware.1-tkg.1
      tanzuCorePackageRepositoryImage:
        imagePath: packages/core/repo
        tag: v1.22.5_vmware.1-tkg.1
      vsphere-cpi.tanzu.vmware.com:
        imagePath: packages/core/vsphere-cpi
        tag: v1.22.4_vmware.1-tkg.1
      vsphere-csi.tanzu.vmware.com:
        imagePath: packages/core/vsphere-csi
        tag: v2.4.1_vmware.1-tkg.1
  vsphere_csi_driver:
  - version: v2.4.1+vmware.1
    images:
      csiControllerImage:
        imagePath: csi/vsphere-block-csi-driver
        tag: v2.4.1_vmware.1
      csiMetaDataSyncerImage:
        imagePath: csi/volume-metadata-syncer
        tag: v2.4.1_vmware.1
  windows-resource-bundle:
  - version: v1.22.5+vmware.1-tkg.1
    images:
      windowsResourceBundleImage:
        imagePath: windows-resource-bundle
        tag: v1.22.5_vmware.1-tkg.1
kubeadmConfigSpec:
  apiVersion: kubeadm.k8s.io/v1beta2
  kind: ClusterConfiguration
  imageRepository: projects.registry.vmware.com/tkg
  kubernetesVersion: v1.22.5+vmware.1
  etcd:
    local:
      dataDir: /var/lib/etcd
      imageRepository: projects.registry.vmware.com/tkg
      imageTag: v3.5.0_vmware.7
  dns:
    type: CoreDNS
    imageRepository: projects.registry.vmware.com/tkg
    imageTag: v1.8.4_vmware.7
ova:
- name: ova-photon-3
  osinfo:
    name: photon
    version: "3"
    arch: amd64
  version: v1.22.5+vmware.1-tkg.2-790a7a702b7fa129fb96be8699f5baa4
- name: ova-ubuntu-2004
  osinfo:
    name: ubuntu
    version: "20.04"
    arch: amd64
  version: v1.22.5+vmware.1-tkg.2-f838b27ca494fee7083c0340e11ce243
ami:
  ap-northeast-1:
  - id: ami-093e2e619f6f1a977
    osinfo:
      name: amazon
      version: "2"
      arch: amd64
  - id: ami-0861cecf34dfe8f1d
    osinfo:
      name: ubuntu
      version: "20.04"
      arch: amd64
  ap-northeast-2:
  - id: ami-04b1576d51c4feb74
    osinfo:
      name: amazon
      version: "2"
      arch: amd64
  - id: ami-09bb05bee117a4252
    osinfo:
      name: ubuntu
      version: "20.04"
      arch: amd64
  ap-south-1:
  - id: ami-0b2bfb2c30f8f588f
    osinfo:
      name: amazon
      version: "2"
      arch: amd64
  - id: ami-09fbea1e5666f8605
    osinfo:
      name: ubuntu
      version: "20.04"
      arch: amd64
  ap-southeast-1:
  - id: ami-02a96c7aa515b9d8e
    osinfo:
      name: amazon
      version: "2"
      arch: amd64
  - id: ami-024a796e5f2499c6b
    osinfo:
      name: ubuntu
      version: "20.04"
      arch: amd64
  ap-southeast-2:
  - id: ami-045b1725fb51c6e85
    osinfo:
      name: amazon
      version: "2"
      arch: amd64
  - id: ami-036d57a6dc1b34a10
    osinfo:
      name: ubuntu
      version: "20.04"
      arch: amd64
  eu-central-1:
  - id: ami-084e2709bd0155912
    osinfo:
      name: amazon
      version: "2"
      arch: amd64
  - id: ami-0278c51f46d54b991
    osinfo:
      name: ubuntu
      version: "20.04"
      arch: amd64
  eu-west-1:
  - id: ami-0ce597d0358a311b1
    osinfo:
      name: amazon
      version: "2"
      arch: amd64
  - id: ami-0b1a2a7cf12202874
    osinfo:
      name: ubuntu
      version: "20.04"
      arch: amd64
  eu-west-2:
  - id: ami-0ae4e47ef44b9b517
    osinfo:
      name: amazon
      version: "2"
      arch: amd64
  - id: ami-0568f06fc5660745f
    osinfo:
      name: ubuntu
      version: "20.04"
      arch: amd64
  eu-west-3:
  - id: ami-0810b5070cb23585f
    osinfo:
      name: amazon
      version: "2"
      arch: amd64
  - id: ami-0600bb078bf5c25b9
    osinfo:
      name: ubuntu
      version: "20.04"
      arch: amd64
  sa-east-1:
  - id: ami-07483a0f62d996f42
    osinfo:
      name: amazon
      version: "2"
      arch: amd64
  - id: ami-0260d3a494d941ed7
    osinfo:
      name: ubuntu
      version: "20.04"
      arch: amd64
  us-east-1:
  - id: ami-0a3064b99b7f3410f
    osinfo:
      name: amazon
      version: "2"
      arch: amd64
  - id: ami-004758cde548c4a76
    osinfo:
      name: ubuntu
      version: "20.04"
      arch: amd64
  us-east-2:
  - id: ami-0b121c081cd4083b5
    osinfo:
      name: amazon
      version: "2"
      arch: amd64
  - id: ami-018b3ce2c63f71edf
    osinfo:
      name: ubuntu
      version: "20.04"
      arch: amd64
  us-gov-east-1:
  - id: ami-08b47d54cf0f2ddf9
    osinfo:
      name: amazon
      version: "2"
      arch: amd64
  - id: ami-0666f05b42dee9a26
    osinfo:
      name: ubuntu
      version: "20.04"
      arch: amd64
  us-gov-west-1:
  - id: ami-093c1de53bf8be69b
    osinfo:
      name: amazon
      version: "2"
      arch: amd64
  - id: ami-06a7b2415646ccb11
    osinfo:
      name: ubuntu
      version: "20.04"
      arch: amd64
  us-west-2:
  - id: ami-0381d0b8fcf481fa2
    osinfo:
      name: amazon
      version: "2"
      arch: amd64
  - id: ami-00acd528b98ef7d45
    osinfo:
      name: ubuntu
      version: "20.04"
      arch: amd64
azure:
- sku: k8s-1dot22dot5-ubuntu-1804
  publisher: vmware-inc
  offer: tkg-capi
  version: 2022.01.27
  thirdPartyImage: true
  osinfo:
    name: ubuntu
    version: "18.04"
    arch: amd64
- sku: k8s-1dot22dot5-ubuntu-2004
  publisher: vmware-inc
  offer: tkg-capi
  version: 2022.01.27
  thirdPartyImage: true
  osinfo:
    name: ubuntu
    version: "20.04"
    arch: amd64
imageConfig:
  imageRepository: projects.registry.vmware.com/tkg
addons:
  ako-operator:
    category: networking
    clusterTypes:
    - management
    packageName: ako-operator.tanzu.vmware.com
  antrea:
    category: cni
    clusterTypes:
    - management
    - workload
    packageName: antrea.tanzu.vmware.com
  calico:
    category: cni
    clusterTypes:
    - management
    - workload
    packageName: calico.tanzu.vmware.com
  kapp-controller:
    category: addons-management
    clusterTypes:
    - management
    - workload
    packageName: kapp-controller.tanzu.vmware.com
  load-balancer-and-ingress-service:
    category: networking
    clusterTypes:
    - management
    - workload
    packageName: load-balancer-and-ingress-service.tanzu.vmware.com
  metrics-server:
    category: metrics
    clusterTypes:
    - management
    - workload
    packageName: metrics-server.tanzu.vmware.com
  pinniped:
    category: authentication
    clusterTypes:
    - management
    - workload
    packageName: pinniped.tanzu.vmware.com
  secretgen-controller:
    category: secret-generation-and-sharing
    clusterTypes:
    - management
    - workload
    packageName: secretgen-controller.tanzu.vmware.com
  tanzu-addons-manager:
    category: addons-management
    clusterTypes:
    - management
    - workload
    packageName: addons-manager.tanzu.vmware.com
  vsphere-cpi:
    category: cpi
    clusterTypes:
    - management
    - workload
    packageName: vsphere-cpi.tanzu.vmware.com
  vsphere-csi:
    category: csi
    clusterTypes:
    - management
    - workload
    packageName: vsphere-csi.tanzu.vmware.com
